### ISSUE TITLE
Use environment variable instead of fixed url in code

### ISSUE THREAD

**Issue by Sandro-Meireles** [weni-ai/weni-integrations-engine#209]
The following lines use a fixed URL instead environment variable. There is already a variable that has the same value `WHATSAPP_API_URL`

https://github.com/weni-ai/weni-integrations-engine/blob/bd0702dbe5d5aeac08eb61f0a7aa2d63c9fcbc01/marketplace/wpp_templates/requests.py#L19

https://github.com/weni-ai/weni-integrations-engine/blob/bd0702dbe5d5aeac08eb61f0a7aa2d63c9fcbc01/marketplace/wpp_templates/requests.py#L27

https://github.com/weni-ai/weni-integrations-engine/blob/bd0702dbe5d5aeac08eb61f0a7aa2d63c9fcbc01/marketplace/wpp_templates/requests.py#L38

https://github.com/weni-ai/weni-integrations-engine/blob/bd0702dbe5d5aeac08eb61f0a7aa2d63c9fcbc01/marketplace/wpp_templates/requests.py#L46

In addition, it would be more interesting to use a method that returns the URL from the endpoint to avoid rework, like: https://github.com/weni-ai/weni-integrations-engine/pull/207/files#diff-1be15eeb5dbb3513b189266691c6b4af6e9c40df745b24f0b2a5d17e844cfeedR28

**Comment by matmsa27** [comment]
This PR #233  fixed change the code to use environment variable.
