### ISSUE TITLE
Responsibility for validating the `name` should be in the `TemplateMessage` model

### ISSUE THREAD

**Issue by Sandro-Meireles** [weni-ai/weni-integrations-engine#220]
https://github.com/weni-ai/weni-integrations-engine/blob/6a3283e3b2a148563fab326f4051c0fdb52985fb/marketplace/wpp_templates/serializers.py#L182

The responsibility of validating the `name` should not be on the Serializer, but on the TemplateMessage model. Models allow creating field validators similar to what is done in the Serializer, this makes it more secure, avoiding possible integrity failures in case a new interface arises to interact with the model.

**Comment by elitonzky** [comment]
Done.
