### ISSUE TITLE
Trying to run a `json.loads()` on a dictionary

### ISSUE THREAD

**Issue by Sandro-Meireles** [weni-ai/weni-integrations-engine#223]
The config received is now returned as a JSON/dict when trying to load it will generate an error and the task will not work!
A pull request has been opened to WhatsApp containing this exact fix: https://github.com/weni-ai/weni-integrations-engine/pull/213

https://github.com/weni-ai/weni-integrations-engine/blob/6a3283e3b2a148563fab326f4051c0fdb52985fb/marketplace/core/types/channels/whatsapp_cloud/tasks.py#L41

**Comment by elitonzky** [comment]
Done
